### PR TITLE
Added contributing guide.

### PR DESCRIPTION
**Pull request by xeioex**

### CODE REVIEW

**Review by VadimZhestikov — DISMISSED** [review]

**Review by VadimZhestikov — DISMISSED** [review]
Looks good

**Comment by mtbChef** [comment]
Overall, it looks great to me. Just some minor suggestions. Another broader one is to change all of the heading and TOC to sentence case. This is what I was asked to do in the Readme as well, so it would be nice if they match styles. Your call though.

**Review by VadimZhestikov — COMMENTED** [review]
Looks good

**Review by VadimZhestikov — APPROVED** [review]
Looks good

**Review by hoeselvank-web — APPROVED** [review]

**Pull request merged**
