### PR TITLE
Fix uninitialized variable in math

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by xeioex** [comment]
Hi @orgads,

How can I reproduce the issue? What compiler do you use?

**Comment by orgads** [comment]
Very old GCC 4.1.2 :)

**Comment by xeioex** [comment]
Hi @orgads,

Unlike nginx, in njs we are not trying to be compatible with any C compiler. 
In nginx there is NGX_SUPPRESS_WARN macro, which allows to put overhead initialization code for compilers which fail to see that initialization is unnecessary.  We do not have such macro in njs.

We are trying to be compatible with modern (available on active and working systems) compilers on UNIX-like systems though.

If you nevertheless want to compile with gcc 4.1 consider providing extra compilation options using `--cc-opt="-w"` to suppress the warnings.

**Comment by orgads** [comment]
Is there a way to pass configure flags when building as a module?

**Comment by xeioex** [comment]
@orgads,

njs build [inherits](https://github.com/nginx/njs/blob/master/nginx/config.make#L6) the CC and CFLAGS from nginx build.

**Comment by orgads** [comment]
I see, thank you.

**Comment by xeioex** [comment]
@orgads 

Just provide `--with-cc-opt='-w'` to nginx configure.

**Pull request closed without merging**
